# -*- coding: utf-8 -*-
"""resumescript.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlK3KUExcvJHIptzgXJQAZ1YML1SY7WR
"""

!pip install python-docx

from google.colab import drive
drive.mount('/content/drive')

import shutil

!pip install transformers

!pip install fuzzywuzzy[speedup]

import os
import spacy
import shutil
import transformers
from docx import Document
from google.colab import files
from google.colab import drive
from transformers import pipeline

from fuzzywuzzy import process
transformers.logging.set_verbosity_error()



ner_pipeline = pipeline('ner', grouped_entities=True)




def extract_text_from_docx(docx_path):
    doc = Document(docx_path)
    return "\n".join([para.text for para in doc.paragraphs])


def extract_name(resume_text, ner_pipeline):
    entities = ner_pipeline(resume_text)
    print(f"NER Entities: {entities}")
    for ent in entities:
        if ent['entity_group'] == 'PER':
            return ent['word'].strip()
    return "Unknown_Name"


def extract_current_job_title(text):

    from fuzzywuzzy import process

def extract_current_job_title(text):
    job_title_keywords = [
        # Software Development and Engineering
        'Software Engineer', 'Full Stack Developer', 'Frontend Developer', 'Backend Developer',
        'Sr. Software Developer', 'Lead Developer', 'Technical Lead', 'Tech Lead', 'Solution Architect',
        'Software Architect', 'Engineering Manager', 'Programmer', 'Embedded Systems Engineer', 'Agile', 'Scrum Master','Sr. Business & Implementation Analyst ','DevOps Engineer', 'Cloud Engineer', 'Systems Engineer', 'Cloud Architect','Business Analyst',

        "Senior Business Analyst",               "Lead Business Analyst",
        "Business Implementation Manager",       "Business Process Analyst",
        "Sr. Implementation Specialist",         "Business Systems Analyst",
        "Senior Implementation Consultant",      "Business Transformation Analyst",
        "Senior Solutions Analyst",              "Business Process Improvement Consultant",
        "Enterprise Business Analyst",           "Senior Business Process Consultant",
        "Business Operations Manager",           "Sr. Change Management Analyst",
        "Senior Business Strategy Consultant",   "IT Business Analyst",
        "Business Intelligence Analyst",         "Data Business Analyst",
        "Product Implementation Manager",        "Business Development Analyst",
        "Senior Project Analyst",                "Business Integration Analyst",
        "Senior Process Analyst",                "Strategic Implementation Manager", 'Sr. iOS Developer',
        "Business Architect",

        # Telecommunications and Networking
        'Telecommunications Engineer', 'Telecommunications Technician', 'Network Engineer', 'Network Administrator',
        'Wireless Engineer', 'RF Engineer', 'Network Architect', 'Telecom Analyst', 'Telecom Manager',
        'Telecom Project Manager', 'Telecom Consultant', 'Telecom Specialist', 'Telecommunications Manager',
        'Voice Network Engineer', 'Fiber Optic Technician', 'Satellite Communications Engineer', 'heterogeneous and complex IT environments',

        # Quality Assurance and Testing
        'QA Engineer', 'QA Tester', 'Quality Assurance Analyst', 'Quality Control Engineer', 'QA Automation Engineer',
        'Test Engineer', 'QA Lead', 'Manual Tester', 'Automation Tester', 'SDET (Software Development Engineer in Test)',
        'Performance Tester', 'Penetration Tester', 'Security Tester', 'Usability Tester',

        # Data Science, AI, and Analytics
        'Data Scientist', 'Data Analyst', 'Machine Learning Engineer', 'AI Engineer', 'Big Data Engineer',
        'Data Engineer', 'Data Architect', 'BI Analyst', 'Business Intelligence Developer', 'Data Visualization Engineer',

        # Management and Leadership Roles (Tech & Non-Tech)
        'Project Manager', 'Program Manager', 'Product Manager', 'IT Manager', 'Technical Project Manager',
        'Development Manager', 'Engineering Manager', 'Team Lead', 'Tech Lead', 'Delivery Manager', 'IT Operations Manager',
        'CTO (Chief Technology Officer)', 'VP of Engineering', 'Director of Engineering', 'Solutions Manager',
        'Digital Transformation Manager', 'Business Development Manager', 'Cloud Operations Manager',

        # DevOps and Infrastructure
        'DevOps Engineer', 'Cloud Engineer', 'Infrastructure Engineer', 'Platform Engineer', 'Systems Engineer',
        'Systems Administrator', 'Cloud Architect', 'Cloud Solutions Architect', 'SRE (Site Reliability Engineer)',
        'Linux Administrator', 'Windows Administrator', 'IT Support Engineer', 'Infrastructure Manager',

        # Security and Compliance
        'Cybersecurity Analyst', 'Security Engineer', 'Security Architect', 'Information Security Manager',
        'Compliance Manager', 'Penetration Tester', 'Vulnerability Assessor', 'Network Security Engineer',
        'Cloud Security Architect',

        # Additional Tech-Related Roles
        'Technical Consultant', 'IT Consultant', 'Solutions Consultant', 'ERP Consultant', 'CRM Consultant',
        'Technical Support Engineer', 'Helpdesk Support', 'Business Analyst', 'Systems Analyst', 'Technology Evangelist',
        "Java Developer",
        "Python Developer",
        "Full Stack Developer",
        "Frontend Developer",
        "Backend Developer",
        "Mobile App Developer",
        "iOS Developer",
        "Android Developer",
        "Node.js Developer",
        "Ruby on Rails Developer",
        "PHP Developer",
        "C# Developer",
        "Angular Developer",
        "React Developer",
        "Vue.js Developer",
        "Django Developer",
        "Spring Boot Developer",
        "DevOps Engineer",
        "Software Engineer",
        "Cloud Developer",

        # Additional QA and Testing-Related Roles
        'Agile Tester', 'Manual Testing', 'Automation Testing', 'Quality Assurance', 'Automation Testing of Web Applications',
        'Mainframe Environment Tester (Waterfall)', 'QA Tester', 'Web Developer', 'Mobile App Developer', 'Python Developer',
        'QA Lead', 'Software Testing & Quality Assurance', 'Manual Tester', 'Senior Network Engineer', 'Software Quality Assurance (SQA)','Network Architect','Android Developer','iOS Developer', 'SDE (Automation or Build or HA)','Java Developer','Java or J2EE Developer', 'Software Engineer', 'Sr. Software Developer','Senior Data Warehouse Architect or Tech Lead','SDE (Automation or Build or HA)',
        'Tech Lead', 'Senior Software Engineer','Team Lead'
    ]

    sentences = text.split('\n')




    for sentence in sentences:


            best_match = process.extractOne(sentence, job_title_keywords)
            if best_match and best_match[1] >= 70:
                return best_match[0]



def save_renamed_file(original_path, name, job_title):
    if name == "Unknown_Name":
        name = "Unknown"
    if job_title == "Job_Title_Not_Found":
        job_title = "No_Job_Title"

    base_dir = '/content/drive/MyDrive/outputresume'
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)
    new_file_name = f"{name}_{job_title}.docx"
    new_file_path = os.path.join(base_dir, new_file_name)

    os.makedirs(base_dir, exist_ok=True)
    shutil.move(original_path, new_file_path)
    return new_file_path

# Main execution block
if __name__ == '__main__':
    uploaded = files.upload()  # Upload resumes in docx format
    resume_paths = list(uploaded.keys())

    for resume_path in resume_paths:
        # Extract resume text
        text = extract_text_from_docx(resume_path)

        # Extract the name using the transformer-based NER pipeline
        name = extract_name(text, ner_pipeline)

        # Extract job title from resume content
        current_job_title = extract_current_job_title(text)

        # Rename and save the file
        new_file = save_renamed_file(resume_path, name, current_job_title)
        print(f"Renamed and saved file as: {new_file}")



